# Generated by Django 5.0.2 on 2024-02-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_category_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='toys',
        ),
    ]
